Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  
  # Script de aprovisionamiento para instalar wrk
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y build-essential libssl-dev git
    git clone https://github.com/wg/wrk.git wrk
    cd wrk
    make
    # Mover wrk al lugar donde todos los usuarios pueden ejecutarlo
    sudo cp wrk /usr/local/bin
  SHELL
end

