Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |app|
    app.vm.provider "docker" do |d|
      d.image = "nginx"
      d.ports = ["8080:80"]
      d.volumes = ["./html:/usr/share/nginx/html"]
      d.remains_running = true
    end
  end
end

